import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1770801356385 implements MigrationInterface {
    name = 'InitialSchema1770801356385'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "plan" character varying NOT NULL DEFAULT 'starter', "status" character varying NOT NULL DEFAULT 'active', "subscription_status" character varying NOT NULL DEFAULT 'trial', "razorpay_customer_id" character varying, "razorpay_subscription_id" character varying, "current_period_end" TIMESTAMP, "monthly_message_limit" integer NOT NULL DEFAULT '1000', "messages_sent_this_month" integer NOT NULL DEFAULT '0', "ai_credits" integer NOT NULL DEFAULT '100', "ai_credits_used" integer NOT NULL DEFAULT '0', "api_access_enabled" boolean NOT NULL DEFAULT false, "webhook_url" character varying, "webhook_secret" character varying, "logo" character varying, "website" character varying, "phone" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2310ecc5cb8be427097154b18f" ON "tenants" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_c59559e7872bc9726adef4669f" ON "tenants" ("status") `);
        await queryRunner.query(`CREATE TABLE "whatsapp_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "business_id" character varying, "waba_id" character varying NOT NULL, "phone_number_id" character varying NOT NULL, "display_phone_number" character varying, "verified_name" character varying, "quality_rating" character varying, "access_token" text, "token_expires_at" TIMESTAMP, "mode" character varying NOT NULL DEFAULT 'coexistence', "status" character varying NOT NULL DEFAULT 'pending', "webhook_verified" boolean NOT NULL DEFAULT false, "messaging_limit" character varying, "last_synced_at" TIMESTAMP, "message_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_02f21802c06f6139e91f5408074" UNIQUE ("tenant_id"), CONSTRAINT "UQ_b261070c7cc1e0149a0000f4f41" UNIQUE ("phone_number_id"), CONSTRAINT "PK_7b68a09f30ca28e87f73c9e844b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02f21802c06f6139e91f540807" ON "whatsapp_accounts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b261070c7cc1e0149a0000f4f4" ON "whatsapp_accounts" ("phone_number_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0866a32a8eb405f6a2e20631cd" ON "whatsapp_accounts" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "phone" character varying, "avatar" character varying, "api_access_enabled" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "email_verified" boolean NOT NULL DEFAULT false, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" character varying NOT NULL, "action" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7331684c0c5b063803a425001a" ON "permissions" ("resource", "action") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_memberships_role_enum" AS ENUM('owner', 'admin', 'agent', 'viewer')`);
        await queryRunner.query(`CREATE TABLE "tenant_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "role_id" uuid, "role" "public"."tenant_memberships_role_enum" NOT NULL DEFAULT 'agent', "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f0363260d50178a78654f4a59f6" UNIQUE ("user_id", "tenant_id"), CONSTRAINT "PK_706d16104745b32d75df5836135" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7427b391abdef33b40124c1582" ON "tenant_memberships" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d22937ebccd641b5090849e51f" ON "tenant_memberships" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "language" character varying, "status" character varying NOT NULL, "components" jsonb, "category" character varying, "lastSyncedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddd7ea53812fb25d98cc335792" ON "templates" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "meta_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token_type" character varying NOT NULL DEFAULT 'system', "encrypted_token" character varying NOT NULL, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43894782234c465cf5b49fd689f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "phone_number" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying, "attributes" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71ec7d68cfafa5f3d93c959b80" ON "contacts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_736eb30c4220859bd55d8e7953" ON "contacts" ("phone_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e503a4350484811a6c3dbf4a2d" ON "contacts" ("tenant_id", "phone_number") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "phone_number_id" character varying NOT NULL, "contact_id" uuid, "assigned_agent" uuid, "status" character varying NOT NULL DEFAULT 'open', "last_message_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_664e8d7cbdae35df5cae341352" ON "conversations" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7a09e158719fa45500ad32de9" ON "conversations" ("phone_number_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9185e4a10f53167d15f23e1720" ON "conversations" ("last_message_at") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "direction" character varying NOT NULL, "type" character varying NOT NULL, "content" jsonb, "status" character varying, "meta_message_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a6bb67478aec10bf144870b91f8" UNIQUE ("meta_message_id"), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bc55a7c3f9ed54b520bb5cfe2" ON "messages" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6bb67478aec10bf144870b91f" ON "messages" ("meta_message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0777b63da90c27d6ed993dc60b" ON "messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e80e763a87656d475402cbf621" ON "messages" ("tenant_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_8584a1974e1ca95f4861d975ff" ON "messages" ("conversation_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "template_id" uuid, "scheduled_at" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'draft', "totalContacts" integer NOT NULL DEFAULT '0', "sentCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d4b32d1e898a336c770e08bf5e" ON "campaigns" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "webhook_endpoints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "url" character varying NOT NULL, "description" character varying, "secret" character varying NOT NULL, "events" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_triggered_at" TIMESTAMP, "failure_count" integer NOT NULL DEFAULT '0', "last_failure_at" TIMESTAMP, "last_failure_reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_054c4cfb95223732f5939d2d546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54847f2dacee9618585993f147" ON "webhook_endpoints" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cb95f1fc8c7b4a2f03243ceb4" ON "webhook_endpoints" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "usage_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "metric" character varying NOT NULL, "value" integer NOT NULL DEFAULT '0', "period_start" date NOT NULL, "period_end" date NOT NULL, CONSTRAINT "PK_14c6ae2b6c1b7114c80fc3c1aec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8014c2ee25eb2bd43fc513fae" ON "usage_metrics" ("tenant_id", "period_start") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('starter', 'growth', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('trial', 'active', 'past_due', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "razorpay_subscription_id" character varying, "razorpay_plan_id" character varying, "razorpay_payment_id" character varying, "plan" "public"."subscriptions_plan_enum" NOT NULL DEFAULT 'starter', "price_inr" integer NOT NULL DEFAULT '1999', "billing_cycle" character varying NOT NULL DEFAULT 'monthly', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'trial', "trial_ends_at" TIMESTAMP, "current_period_start" TIMESTAMP, "current_period_end" TIMESTAMP, "cancelled_at" TIMESTAMP, "monthly_messages" integer NOT NULL DEFAULT '10000', "ai_credits" integer NOT NULL DEFAULT '1000', "max_agents" integer NOT NULL DEFAULT '1', "api_access" boolean NOT NULL DEFAULT false, "custom_templates" boolean NOT NULL DEFAULT false, "white_label" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6ac03431c311ccb8bbd7d3af1" ON "subscriptions" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE TABLE "razorpay_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventId" character varying NOT NULL, "event" character varying NOT NULL, "payload" jsonb, "status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0dc0a37e70cdb3c89a2160e79d3" UNIQUE ("eventId"), CONSTRAINT "PK_ea319a2de13baf2804ef8112df9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0dc0a37e70cdb3c89a2160e79d" ON "razorpay_events" ("eventId") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "key_prefix" character varying NOT NULL, "key_hash" character varying NOT NULL, "permissions" text, "is_active" boolean NOT NULL DEFAULT true, "last_used_at" TIMESTAMP, "expires_at" TIMESTAMP, "rate_limit" integer NOT NULL DEFAULT '100', "requests_today" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ac18429c8d27858d79432e0dd" ON "api_keys" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_138cc6196c7bfa61d31412aea7" ON "api_keys" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "automation_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "trigger" character varying NOT NULL, "condition" character varying NOT NULL, "keyword" character varying NOT NULL, "action" character varying NOT NULL, "payload" jsonb NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_378bed501eacc036895837121c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99d39abb380b35f95b180c6ab8" ON "automation_rules" ("tenant_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_level_enum" AS ENUM('info', 'success', 'warning', 'error')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_category_enum" AS ENUM('system', 'user', 'security', 'billing', 'whatsapp', 'ai')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" character varying, "tenant_id" character varying, "actorName" character varying NOT NULL, "action" character varying NOT NULL, "target" character varying NOT NULL, "metadata" jsonb, "ipAddress" character varying, "level" "public"."audit_logs_level_enum" NOT NULL DEFAULT 'info', "category" "public"."audit_logs_category_enum" NOT NULL DEFAULT 'system', "source" character varying, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ai_agents_type_enum" AS ENUM('customer_support', 'sales', 'lead_followup', 'faq', 'custom')`);
        await queryRunner.query(`CREATE TABLE "ai_agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "type" "public"."ai_agents_type_enum" NOT NULL DEFAULT 'customer_support', "system_prompt" text NOT NULL, "welcome_message" text, "fallback_message" text, "confidence_threshold" numeric(3,2) NOT NULL DEFAULT '0.7', "max_context_messages" integer NOT NULL DEFAULT '10', "model" character varying NOT NULL DEFAULT 'gemini-pro', "temperature" numeric(2,1) NOT NULL DEFAULT '0.7', "max_tokens" integer NOT NULL DEFAULT '500', "is_active" boolean NOT NULL DEFAULT true, "handoff_enabled" boolean NOT NULL DEFAULT true, "handoff_keywords" text, "business_hours_only" boolean NOT NULL DEFAULT false, "knowledge_base" text, "sample_conversations" text, "total_conversations" integer NOT NULL DEFAULT '0', "successful_resolutions" integer NOT NULL DEFAULT '0', "handoffs_triggered" integer NOT NULL DEFAULT '0', "avg_response_time_ms" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_38dae00b19ff837456f29681e8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b35f04bbc39faaf4516a32528d" ON "ai_agents" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_10f9bfef8efbec7094e96f46f7" ON "ai_agents" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "system_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text NOT NULL, "description" character varying, "isSecret" boolean NOT NULL DEFAULT false, "category" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_eedd3cd0f227c7fb5eff2204e93" UNIQUE ("key"), CONSTRAINT "PK_db4e70ac0d27e588176e9bb44a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "whatsapp_accounts" ADD CONSTRAINT "FK_02f21802c06f6139e91f5408074" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" ADD CONSTRAINT "FK_7427b391abdef33b40124c15822" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" ADD CONSTRAINT "FK_d22937ebccd641b5090849e51f7" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" ADD CONSTRAINT "FK_fa9ba14be22683296a780a57c6f" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "FK_ddd7ea53812fb25d98cc3357926" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_71ec7d68cfafa5f3d93c959b807" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_664e8d7cbdae35df5cae341352a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_3e605129623b629ddd0583740db" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_b0680469a10bc0521800431abab" FOREIGN KEY ("assigned_agent") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_558150f45586066db2415eb28c5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_d4b32d1e898a336c770e08bf5e8" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_e7710203c0b031e01de765c25e7" FOREIGN KEY ("template_id") REFERENCES "templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "FK_54847f2dacee9618585993f1474" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_metrics" ADD CONSTRAINT "FK_ba294a228284c2fdd5ce888d8d5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_f6ac03431c311ccb8bbd7d3af18" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_keys" ADD CONSTRAINT "FK_3ac18429c8d27858d79432e0dda" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "automation_rules" ADD CONSTRAINT "FK_99d39abb380b35f95b180c6ab8c" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_agents" ADD CONSTRAINT "FK_b35f04bbc39faaf4516a32528df" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_agents" DROP CONSTRAINT "FK_b35f04bbc39faaf4516a32528df"`);
        await queryRunner.query(`ALTER TABLE "automation_rules" DROP CONSTRAINT "FK_99d39abb380b35f95b180c6ab8c"`);
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_3ac18429c8d27858d79432e0dda"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_f6ac03431c311ccb8bbd7d3af18"`);
        await queryRunner.query(`ALTER TABLE "usage_metrics" DROP CONSTRAINT "FK_ba294a228284c2fdd5ce888d8d5"`);
        await queryRunner.query(`ALTER TABLE "webhook_endpoints" DROP CONSTRAINT "FK_54847f2dacee9618585993f1474"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_e7710203c0b031e01de765c25e7"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_d4b32d1e898a336c770e08bf5e8"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_558150f45586066db2415eb28c5"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_b0680469a10bc0521800431abab"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_3e605129623b629ddd0583740db"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_664e8d7cbdae35df5cae341352a"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_71ec7d68cfafa5f3d93c959b807"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "FK_ddd7ea53812fb25d98cc3357926"`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" DROP CONSTRAINT "FK_fa9ba14be22683296a780a57c6f"`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" DROP CONSTRAINT "FK_d22937ebccd641b5090849e51f7"`);
        await queryRunner.query(`ALTER TABLE "tenant_memberships" DROP CONSTRAINT "FK_7427b391abdef33b40124c15822"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_accounts" DROP CONSTRAINT "FK_02f21802c06f6139e91f5408074"`);
        await queryRunner.query(`DROP TABLE "system_config"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10f9bfef8efbec7094e96f46f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b35f04bbc39faaf4516a32528d"`);
        await queryRunner.query(`DROP TABLE "ai_agents"`);
        await queryRunner.query(`DROP TYPE "public"."ai_agents_type_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99d39abb380b35f95b180c6ab8"`);
        await queryRunner.query(`DROP TABLE "automation_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_138cc6196c7bfa61d31412aea7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ac18429c8d27858d79432e0dd"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0dc0a37e70cdb3c89a2160e79d"`);
        await queryRunner.query(`DROP TABLE "razorpay_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6ac03431c311ccb8bbd7d3af1"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8014c2ee25eb2bd43fc513fae"`);
        await queryRunner.query(`DROP TABLE "usage_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cb95f1fc8c7b4a2f03243ceb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54847f2dacee9618585993f147"`);
        await queryRunner.query(`DROP TABLE "webhook_endpoints"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4b32d1e898a336c770e08bf5e"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8584a1974e1ca95f4861d975ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e80e763a87656d475402cbf621"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0777b63da90c27d6ed993dc60b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6bb67478aec10bf144870b91f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc55a7c3f9ed54b520bb5cfe2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9185e4a10f53167d15f23e1720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7a09e158719fa45500ad32de9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_664e8d7cbdae35df5cae341352"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e503a4350484811a6c3dbf4a2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_736eb30c4220859bd55d8e7953"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71ec7d68cfafa5f3d93c959b80"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP TABLE "meta_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddd7ea53812fb25d98cc335792"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d22937ebccd641b5090849e51f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7427b391abdef33b40124c1582"`);
        await queryRunner.query(`DROP TABLE "tenant_memberships"`);
        await queryRunner.query(`DROP TYPE "public"."tenant_memberships_role_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7331684c0c5b063803a425001a"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0866a32a8eb405f6a2e20631cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b261070c7cc1e0149a0000f4f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02f21802c06f6139e91f540807"`);
        await queryRunner.query(`DROP TABLE "whatsapp_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59559e7872bc9726adef4669f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2310ecc5cb8be427097154b18f"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
    }

}
