
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import Navigation from "@/components/Navigation";
import { HelpCircle, Sparkles, Shield, Globe, Search, Headphones } from "lucide-react";

const FAQ = () => {
  const categories = [
    {
      title: "AI Content Generation",
      icon: Sparkles,
      faqs: [
        {
          question: "How does the AI write content?",
          answer: "Aerostic AI uses Google's advanced Gemini AI model to generate high-quality blog posts. Simply provide a topic, choose your preferred tone, and our AI analyzes millions of data points to create engaging, relevant content tailored to your audience."
        },
        {
          question: "Can I customize the AI's writing style?",
          answer: "Absolutely! You can choose from various writing tones including Friendly, Professional, Casual, Authoritative, and Humorous. The AI adapts to match your preferred style and voice."
        },
        {
          question: "How accurate and original is the AI-generated content?",
          answer: "The AI generates original content based on your specific prompts. All content is unique and not copied from existing sources. However, we recommend reviewing and editing the content to ensure it perfectly matches your brand voice."
        },
        {
          question: "Can the AI write in different languages?",
          answer: "Currently, Aerostic AI primarily supports English content generation. We're working on adding support for multiple languages in future updates."
        }
      ]
    },
    {
      title: "Security & Privacy",
      icon: Shield,
      faqs: [
        {
          question: "How secure is my website and data?",
          answer: "Security is our top priority. All websites are hosted on secure, encrypted servers with SSL certificates. Your data is protected with enterprise-grade security measures, regular backups, and we comply with GDPR and privacy regulations."
        },
        {
          question: "Who owns the content created by AI?",
          answer: "You own all the content generated by our AI. Once created, the content belongs entirely to you and can be used however you see fit."
        },
        {
          question: "Do you store my blog content?",
          answer: "We store your blog content securely to enable features like editing, scheduling, and analytics. You can export or delete your content at any time. We never share your content with third parties."
        }
      ]
    },
    {
      title: "Domain & Website Management",
      icon: Globe,
      faqs: [
        {
          question: "Can I connect my own custom domain?",
          answer: "Yes! Professional plan users can connect their own custom domain (like yoursite.com). We provide step-by-step instructions for domain setup and handle all the technical configuration."
        },
        {
          question: "What happens if I want to move my blog elsewhere?",
          answer: "You can export all your content at any time. We provide full content exports in standard formats that can be imported into other blogging platforms."
        },
        {
          question: "How reliable is the hosting?",
          answer: "We guarantee 99.9% uptime with our enterprise hosting infrastructure. Your blog is hosted on fast, reliable servers with automatic backups and global CDN for optimal performance worldwide."
        },
        {
          question: "Can I have multiple blogs on one account?",
          answer: "Creator plans include one blog, while Professional plans allow up to 3 blogs. Contact us for enterprise solutions if you need more blogs."
        }
      ]
    },
    {
      title: "SEO & Analytics",
      icon: Search,
      faqs: [
        {
          question: "How does SEO optimization work?",
          answer: "Our AI automatically optimizes your content for search engines by analyzing keywords, creating meta descriptions, optimizing headings, and ensuring proper content structure. We also provide SEO suggestions and connect with Google Search Console."
        },
        {
          question: "What analytics are included?",
          answer: "You get comprehensive analytics including page views, visitor demographics, popular content, traffic sources, and engagement metrics. Professional plans include advanced analytics with detailed insights."
        },
        {
          question: "Can I track my search engine rankings?",
          answer: "Yes, Professional plans include Google Search Console integration that tracks your search rankings, click-through rates, and search performance metrics."
        }
      ]
    },
    {
      title: "Support & Billing",
      icon: Headphones,
      faqs: [
        {
          question: "What support options are available?",
          answer: "Free trial users get community support, Creator plan users receive email support, and Professional users get priority support with faster response times. All plans include our comprehensive knowledge base."
        },
        {
          question: "Can I cancel my subscription anytime?",
          answer: "Yes, you can cancel your subscription at any time. Your blog will remain active until the end of your current billing period. No cancellation fees apply."
        },
        {
          question: "Do you offer refunds?",
          answer: "We offer a 30-day money-back guarantee for all paid plans. If you're not satisfied within the first 30 days, we'll provide a full refund."
        },
        {
          question: "How does billing work for add-ons?",
          answer: "Add-ons are billed monthly alongside your main subscription. You can add or remove add-ons at any time, and changes take effect on your next billing cycle."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen gradient-bg">
      <Navigation />
      
      <div className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-16">
            <HelpCircle className="h-12 w-12 text-primary mx-auto mb-4" />
            <h1 className="text-4xl font-bold text-gray-900 mb-6">
              Frequently Asked Questions
            </h1>
            <p className="text-xl text-gray-600">
              Find answers to common questions about Aerostic AI
            </p>
          </div>

          {/* FAQ Categories */}
          <div className="space-y-8">
            {categories.map((category, categoryIndex) => (
              <Card key={categoryIndex}>
                <CardHeader>
                  <CardTitle className="flex items-center text-xl">
                    <category.icon className="h-6 w-6 text-primary mr-3" />
                    {category.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <Accordion type="single" collapsible>
                    {category.faqs.map((faq, faqIndex) => (
                      <AccordionItem key={faqIndex} value={`item-${categoryIndex}-${faqIndex}`}>
                        <AccordionTrigger className="text-left">
                          {faq.question}
                        </AccordionTrigger>
                        <AccordionContent className="text-gray-600">
                          {faq.answer}
                        </AccordionContent>
                      </AccordionItem>
                    ))}
                  </Accordion>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Contact CTA */}
          <div className="mt-16 text-center bg-white/70 rounded-2xl p-8">
            <h2 className="text-2xl font-bold mb-4">Still have questions?</h2>
            <p className="text-gray-600 mb-6">
              Can't find the answer you're looking for? Our support team is here to help.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a 
                href="/contact" 
                className="inline-flex items-center justify-center px-6 py-3 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
              >
                Contact Support
              </a>
              <a 
                href="/blog-editor" 
                className="inline-flex items-center justify-center px-6 py-3 border border-primary text-primary rounded-lg hover:bg-primary/5 transition-colors"
              >
                Try It Free
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
