// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsyxndzqsadatwcbbdrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeXhuZHpxc2FkYXR3Y2JiZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzAzOTgsImV4cCI6MjA2NjQ0NjM5OH0.Mxo8pWZcn0PMUBRhqwEDuRNctLDCSQlKDLGFJEUkYIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);